# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d37f860481ae3ba58298d73739202cf0732277a041f894596eef9dba056d71474f2edd82f1f4643372f64f803fc85740214e02dc82e0c28b50d4f852ba9f8b7b

test:
  secret_key_base: eb02d3c943a547ec5233e8ae3cc0e9a2fff4a82575951b7110478a0a30beb7dec2c39d90426c69334a4c2400f12c61cc37773aee9b4039433dfbc14eb5c40b1f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= Figaro.env.secret_key_base %>
